# Site settings
title: Introduction to Making Web Pages
description: Tutorial for learning the basics of web development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://web-intro.vesavanska.com" # the base hostname & protocol for your site

navigation:
  - title: 0. Installation
    url: /install/
  - title: 1. HTML
    url: /html/
  - title: 2. CSS
    url: /css/
